package diana.maven.project.mappers;

import diana.maven.project.models.CreditType;
import diana.maven.project.models.CreditTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(CreditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(CreditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(CreditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(CreditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<CreditType> selectByExample(CreditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    CreditType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") CreditType record, @Param("example") CreditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") CreditType record, @Param("example") CreditTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(CreditType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(CreditType record);
}