package diana.maven.project.mappers;

import diana.maven.project.models.CreditSubject;
import diana.maven.project.models.CreditSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(CreditSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(CreditSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(CreditSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(CreditSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<CreditSubject> selectByExample(CreditSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    CreditSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") CreditSubject record, @Param("example") CreditSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") CreditSubject record, @Param("example") CreditSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(CreditSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(CreditSubject record);
}