package diana.maven.project.mappers;

import diana.maven.project.models.PermissionService;
import diana.maven.project.models.PermissionServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(PermissionServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(PermissionServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(PermissionService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(PermissionService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<PermissionService> selectByExample(PermissionServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    PermissionService selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PermissionService record, @Param("example") PermissionServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") PermissionService record, @Param("example") PermissionServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(PermissionService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(PermissionService record);
}