package diana.maven.project.mappers;

import diana.maven.project.models.PlatformRole;
import diana.maven.project.models.PlatformRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(PlatformRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(PlatformRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<PlatformRole> selectByExample(PlatformRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    PlatformRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlatformRole record, @Param("example") PlatformRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") PlatformRole record, @Param("example") PlatformRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(PlatformRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(PlatformRole record);
}