package diana.maven.project.models;

import java.util.ArrayList;
import java.util.List;

public class CreditTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public CreditTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdIsNull() {
            addCriterion("credit_subject_type_id is null");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdIsNotNull() {
            addCriterion("credit_subject_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdEqualTo(Integer value) {
            addCriterion("credit_subject_type_id =", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdNotEqualTo(Integer value) {
            addCriterion("credit_subject_type_id <>", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdGreaterThan(Integer value) {
            addCriterion("credit_subject_type_id >", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("credit_subject_type_id >=", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdLessThan(Integer value) {
            addCriterion("credit_subject_type_id <", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("credit_subject_type_id <=", value, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdIn(List<Integer> values) {
            addCriterion("credit_subject_type_id in", values, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdNotIn(List<Integer> values) {
            addCriterion("credit_subject_type_id not in", values, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("credit_subject_type_id between", value1, value2, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("credit_subject_type_id not between", value1, value2, "creditSubjectTypeId");
            return (Criteria) this;
        }

        public Criteria andLockedIsNull() {
            addCriterion("locked is null");
            return (Criteria) this;
        }

        public Criteria andLockedIsNotNull() {
            addCriterion("locked is not null");
            return (Criteria) this;
        }

        public Criteria andLockedEqualTo(String value) {
            addCriterion("locked =", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotEqualTo(String value) {
            addCriterion("locked <>", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedGreaterThan(String value) {
            addCriterion("locked >", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedGreaterThanOrEqualTo(String value) {
            addCriterion("locked >=", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLessThan(String value) {
            addCriterion("locked <", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLessThanOrEqualTo(String value) {
            addCriterion("locked <=", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedLike(String value) {
            addCriterion("locked like", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotLike(String value) {
            addCriterion("locked not like", value, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedIn(List<String> values) {
            addCriterion("locked in", values, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotIn(List<String> values) {
            addCriterion("locked not in", values, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedBetween(String value1, String value2) {
            addCriterion("locked between", value1, value2, "locked");
            return (Criteria) this;
        }

        public Criteria andLockedNotBetween(String value1, String value2) {
            addCriterion("locked not between", value1, value2, "locked");
            return (Criteria) this;
        }

        public Criteria andCreditNameIsNull() {
            addCriterion("credit_name is null");
            return (Criteria) this;
        }

        public Criteria andCreditNameIsNotNull() {
            addCriterion("credit_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreditNameEqualTo(String value) {
            addCriterion("credit_name =", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameNotEqualTo(String value) {
            addCriterion("credit_name <>", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameGreaterThan(String value) {
            addCriterion("credit_name >", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameGreaterThanOrEqualTo(String value) {
            addCriterion("credit_name >=", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameLessThan(String value) {
            addCriterion("credit_name <", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameLessThanOrEqualTo(String value) {
            addCriterion("credit_name <=", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameLike(String value) {
            addCriterion("credit_name like", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameNotLike(String value) {
            addCriterion("credit_name not like", value, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameIn(List<String> values) {
            addCriterion("credit_name in", values, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameNotIn(List<String> values) {
            addCriterion("credit_name not in", values, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameBetween(String value1, String value2) {
            addCriterion("credit_name between", value1, value2, "creditName");
            return (Criteria) this;
        }

        public Criteria andCreditNameNotBetween(String value1, String value2) {
            addCriterion("credit_name not between", value1, value2, "creditName");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsIsNull() {
            addCriterion("deduction_of_points is null");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsIsNotNull() {
            addCriterion("deduction_of_points is not null");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsEqualTo(Integer value) {
            addCriterion("deduction_of_points =", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsNotEqualTo(Integer value) {
            addCriterion("deduction_of_points <>", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsGreaterThan(Integer value) {
            addCriterion("deduction_of_points >", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("deduction_of_points >=", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsLessThan(Integer value) {
            addCriterion("deduction_of_points <", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsLessThanOrEqualTo(Integer value) {
            addCriterion("deduction_of_points <=", value, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsIn(List<Integer> values) {
            addCriterion("deduction_of_points in", values, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsNotIn(List<Integer> values) {
            addCriterion("deduction_of_points not in", values, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsBetween(Integer value1, Integer value2) {
            addCriterion("deduction_of_points between", value1, value2, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andDeductionOfPointsNotBetween(Integer value1, Integer value2) {
            addCriterion("deduction_of_points not between", value1, value2, "deductionOfPoints");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_type
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 28 11:26:14 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}