package net.yto.newmysql.mappers;

import java.util.List;
import net.yto.newmysql.models.StudentEntity;
import net.yto.newmysql.models.StudentEntityExample;
import net.yto.webframework.persistence.mappers.MapperMarkerInterface;

import org.apache.ibatis.annotations.Param;

public interface StudentEntityMapper extends MapperMarkerInterface{
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	long countByExample(StudentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int deleteByExample(StudentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int insert(StudentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int insertSelective(StudentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	List<StudentEntity> selectByExample(StudentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	StudentEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByExampleSelective(@Param("record") StudentEntity record, @Param("example") StudentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByExample(@Param("record") StudentEntity record, @Param("example") StudentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByPrimaryKeySelective(StudentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByPrimaryKey(StudentEntity record);

	/**
     * 无条件获取所有学生信�?
     * @return
     */
    List<StudentEntity> getAllStudent();
}