package net.yto.newmysql.mappers;

import java.util.List;
import net.yto.newmysql.models.UserEntity;
import net.yto.newmysql.models.UserEntityExample;
import net.yto.webframework.persistence.mappers.MapperMarkerInterface;

import org.apache.ibatis.annotations.Param;
import net.yto.newmysql.models.UserEntityWithBLOBs;

public interface UserEntityMapper extends MapperMarkerInterface{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	long countByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int deleteByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int insert(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int insertSelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	List<UserEntity> selectByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	UserEntity selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByExampleSelective(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByExample(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByPrimaryKeySelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Tue May 07 10:41:13 CST 2019
	 */
	int updateByPrimaryKey(UserEntity record);
}