package diana.maven.project.model;

public class CreditSubjectType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject_type.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject_type.id
     *
     * @return the value of credit_subject_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject_type.id
     *
     * @param id the value for credit_subject_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject_type.name
     *
     * @return the value of credit_subject_type.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject_type.name
     *
     * @param name the value for credit_subject_type.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject_type.is_del
     *
     * @return the value of credit_subject_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject_type.is_del
     *
     * @param isDel the value for credit_subject_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}