package diana.maven.project.model;

import java.util.Date;

public class CreditRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.record_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String recordCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer creditSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer creditType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String attachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.reporter
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer reporter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.report_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date reportTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.verifier
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String verifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.verifier_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date verifierTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.verifier_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String verifierContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.appealer
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer appealer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.appeal_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date appealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.appeal_attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String appealAttachment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.appeal_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String appealContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.status
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.remark
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_record.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.id
     *
     * @return the value of credit_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.id
     *
     * @param id the value for credit_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.record_code
     *
     * @return the value of credit_record.record_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getRecordCode() {
        return recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.record_code
     *
     * @param recordCode the value for credit_record.record_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setRecordCode(String recordCode) {
        this.recordCode = recordCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.credit_subject
     *
     * @return the value of credit_record.credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getCreditSubject() {
        return creditSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.credit_subject
     *
     * @param creditSubject the value for credit_record.credit_subject
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditSubject(Integer creditSubject) {
        this.creditSubject = creditSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.credit_type
     *
     * @return the value of credit_record.credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getCreditType() {
        return creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.credit_type
     *
     * @param creditType the value for credit_record.credit_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditType(Integer creditType) {
        this.creditType = creditType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.attachment
     *
     * @return the value of credit_record.attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.attachment
     *
     * @param attachment the value for credit_record.attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.reporter
     *
     * @return the value of credit_record.reporter
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getReporter() {
        return reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.reporter
     *
     * @param reporter the value for credit_record.reporter
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setReporter(Integer reporter) {
        this.reporter = reporter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.report_time
     *
     * @return the value of credit_record.report_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.report_time
     *
     * @param reportTime the value for credit_record.report_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.verifier
     *
     * @return the value of credit_record.verifier
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getVerifier() {
        return verifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.verifier
     *
     * @param verifier the value for credit_record.verifier
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setVerifier(String verifier) {
        this.verifier = verifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.verifier_time
     *
     * @return the value of credit_record.verifier_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getVerifierTime() {
        return verifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.verifier_time
     *
     * @param verifierTime the value for credit_record.verifier_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setVerifierTime(Date verifierTime) {
        this.verifierTime = verifierTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.verifier_context
     *
     * @return the value of credit_record.verifier_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getVerifierContext() {
        return verifierContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.verifier_context
     *
     * @param verifierContext the value for credit_record.verifier_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setVerifierContext(String verifierContext) {
        this.verifierContext = verifierContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.appealer
     *
     * @return the value of credit_record.appealer
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getAppealer() {
        return appealer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.appealer
     *
     * @param appealer the value for credit_record.appealer
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setAppealer(Integer appealer) {
        this.appealer = appealer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.appeal_time
     *
     * @return the value of credit_record.appeal_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getAppealTime() {
        return appealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.appeal_time
     *
     * @param appealTime the value for credit_record.appeal_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setAppealTime(Date appealTime) {
        this.appealTime = appealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.appeal_attachment
     *
     * @return the value of credit_record.appeal_attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getAppealAttachment() {
        return appealAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.appeal_attachment
     *
     * @param appealAttachment the value for credit_record.appeal_attachment
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setAppealAttachment(String appealAttachment) {
        this.appealAttachment = appealAttachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.appeal_context
     *
     * @return the value of credit_record.appeal_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getAppealContext() {
        return appealContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.appeal_context
     *
     * @param appealContext the value for credit_record.appeal_context
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setAppealContext(String appealContext) {
        this.appealContext = appealContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.status
     *
     * @return the value of credit_record.status
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.status
     *
     * @param status the value for credit_record.status
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.remark
     *
     * @return the value of credit_record.remark
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.remark
     *
     * @param remark the value for credit_record.remark
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_record.is_del
     *
     * @return the value of credit_record.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_record.is_del
     *
     * @param isDel the value for credit_record.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}