package diana.maven.project.model;

public class CreditSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.gender
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.credit_subject_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer creditSubjectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.score
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String unitsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String subordinateUnits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.cellphone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String cellphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.telephone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.email
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.website
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_subject.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.id
     *
     * @return the value of credit_subject.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.id
     *
     * @param id the value for credit_subject.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.name
     *
     * @return the value of credit_subject.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.name
     *
     * @param name the value for credit_subject.name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.credit_code
     *
     * @return the value of credit_subject.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.credit_code
     *
     * @param creditCode the value for credit_subject.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.gender
     *
     * @return the value of credit_subject.gender
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.gender
     *
     * @param gender the value for credit_subject.gender
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.credit_subject_type
     *
     * @return the value of credit_subject.credit_subject_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getCreditSubjectType() {
        return creditSubjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.credit_subject_type
     *
     * @param creditSubjectType the value for credit_subject.credit_subject_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditSubjectType(Integer creditSubjectType) {
        this.creditSubjectType = creditSubjectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.score
     *
     * @return the value of credit_subject.score
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.score
     *
     * @param score the value for credit_subject.score
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.units_code
     *
     * @return the value of credit_subject.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getUnitsCode() {
        return unitsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.units_code
     *
     * @param unitsCode the value for credit_subject.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setUnitsCode(String unitsCode) {
        this.unitsCode = unitsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.subordinate_units
     *
     * @return the value of credit_subject.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getSubordinateUnits() {
        return subordinateUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.subordinate_units
     *
     * @param subordinateUnits the value for credit_subject.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setSubordinateUnits(String subordinateUnits) {
        this.subordinateUnits = subordinateUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.cellphone
     *
     * @return the value of credit_subject.cellphone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.cellphone
     *
     * @param cellphone the value for credit_subject.cellphone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.telephone
     *
     * @return the value of credit_subject.telephone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.telephone
     *
     * @param telephone the value for credit_subject.telephone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.email
     *
     * @return the value of credit_subject.email
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.email
     *
     * @param email the value for credit_subject.email
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.website
     *
     * @return the value of credit_subject.website
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.website
     *
     * @param website the value for credit_subject.website
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_subject.is_del
     *
     * @return the value of credit_subject.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_subject.is_del
     *
     * @param isDel the value for credit_subject.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}