package diana.maven.project.model;

public class CreditType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.credit_subject_type_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer creditSubjectTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.credit_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String creditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.deduction_of_points
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer deductionOfPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.id
     *
     * @return the value of credit_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.id
     *
     * @param id the value for credit_type.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.credit_subject_type_id
     *
     * @return the value of credit_type.credit_subject_type_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getCreditSubjectTypeId() {
        return creditSubjectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.credit_subject_type_id
     *
     * @param creditSubjectTypeId the value for credit_type.credit_subject_type_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditSubjectTypeId(Integer creditSubjectTypeId) {
        this.creditSubjectTypeId = creditSubjectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.locked
     *
     * @return the value of credit_type.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.locked
     *
     * @param locked the value for credit_type.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setLocked(String locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.credit_name
     *
     * @return the value of credit_type.credit_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getCreditName() {
        return creditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.credit_name
     *
     * @param creditName the value for credit_type.credit_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditName(String creditName) {
        this.creditName = creditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.deduction_of_points
     *
     * @return the value of credit_type.deduction_of_points
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getDeductionOfPoints() {
        return deductionOfPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.deduction_of_points
     *
     * @param deductionOfPoints the value for credit_type.deduction_of_points
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setDeductionOfPoints(Integer deductionOfPoints) {
        this.deductionOfPoints = deductionOfPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column credit_type.is_del
     *
     * @return the value of credit_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column credit_type.is_del
     *
     * @param isDel the value for credit_type.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}