package diana.maven.project.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CreditRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public CreditRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIsNull() {
            addCriterion("record_code is null");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIsNotNull() {
            addCriterion("record_code is not null");
            return (Criteria) this;
        }

        public Criteria andRecordCodeEqualTo(String value) {
            addCriterion("record_code =", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotEqualTo(String value) {
            addCriterion("record_code <>", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeGreaterThan(String value) {
            addCriterion("record_code >", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeGreaterThanOrEqualTo(String value) {
            addCriterion("record_code >=", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLessThan(String value) {
            addCriterion("record_code <", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLessThanOrEqualTo(String value) {
            addCriterion("record_code <=", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeLike(String value) {
            addCriterion("record_code like", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotLike(String value) {
            addCriterion("record_code not like", value, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeIn(List<String> values) {
            addCriterion("record_code in", values, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotIn(List<String> values) {
            addCriterion("record_code not in", values, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeBetween(String value1, String value2) {
            addCriterion("record_code between", value1, value2, "recordCode");
            return (Criteria) this;
        }

        public Criteria andRecordCodeNotBetween(String value1, String value2) {
            addCriterion("record_code not between", value1, value2, "recordCode");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectIsNull() {
            addCriterion("credit_subject is null");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectIsNotNull() {
            addCriterion("credit_subject is not null");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectEqualTo(Integer value) {
            addCriterion("credit_subject =", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectNotEqualTo(Integer value) {
            addCriterion("credit_subject <>", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectGreaterThan(Integer value) {
            addCriterion("credit_subject >", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectGreaterThanOrEqualTo(Integer value) {
            addCriterion("credit_subject >=", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectLessThan(Integer value) {
            addCriterion("credit_subject <", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectLessThanOrEqualTo(Integer value) {
            addCriterion("credit_subject <=", value, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectIn(List<Integer> values) {
            addCriterion("credit_subject in", values, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectNotIn(List<Integer> values) {
            addCriterion("credit_subject not in", values, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectBetween(Integer value1, Integer value2) {
            addCriterion("credit_subject between", value1, value2, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditSubjectNotBetween(Integer value1, Integer value2) {
            addCriterion("credit_subject not between", value1, value2, "creditSubject");
            return (Criteria) this;
        }

        public Criteria andCreditTypeIsNull() {
            addCriterion("credit_type is null");
            return (Criteria) this;
        }

        public Criteria andCreditTypeIsNotNull() {
            addCriterion("credit_type is not null");
            return (Criteria) this;
        }

        public Criteria andCreditTypeEqualTo(Integer value) {
            addCriterion("credit_type =", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeNotEqualTo(Integer value) {
            addCriterion("credit_type <>", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeGreaterThan(Integer value) {
            addCriterion("credit_type >", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("credit_type >=", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeLessThan(Integer value) {
            addCriterion("credit_type <", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeLessThanOrEqualTo(Integer value) {
            addCriterion("credit_type <=", value, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeIn(List<Integer> values) {
            addCriterion("credit_type in", values, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeNotIn(List<Integer> values) {
            addCriterion("credit_type not in", values, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeBetween(Integer value1, Integer value2) {
            addCriterion("credit_type between", value1, value2, "creditType");
            return (Criteria) this;
        }

        public Criteria andCreditTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("credit_type not between", value1, value2, "creditType");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNull() {
            addCriterion("attachment is null");
            return (Criteria) this;
        }

        public Criteria andAttachmentIsNotNull() {
            addCriterion("attachment is not null");
            return (Criteria) this;
        }

        public Criteria andAttachmentEqualTo(String value) {
            addCriterion("attachment =", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotEqualTo(String value) {
            addCriterion("attachment <>", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThan(String value) {
            addCriterion("attachment >", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("attachment >=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThan(String value) {
            addCriterion("attachment <", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLessThanOrEqualTo(String value) {
            addCriterion("attachment <=", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentLike(String value) {
            addCriterion("attachment like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotLike(String value) {
            addCriterion("attachment not like", value, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentIn(List<String> values) {
            addCriterion("attachment in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotIn(List<String> values) {
            addCriterion("attachment not in", values, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentBetween(String value1, String value2) {
            addCriterion("attachment between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andAttachmentNotBetween(String value1, String value2) {
            addCriterion("attachment not between", value1, value2, "attachment");
            return (Criteria) this;
        }

        public Criteria andReporterIsNull() {
            addCriterion("reporter is null");
            return (Criteria) this;
        }

        public Criteria andReporterIsNotNull() {
            addCriterion("reporter is not null");
            return (Criteria) this;
        }

        public Criteria andReporterEqualTo(Integer value) {
            addCriterion("reporter =", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterNotEqualTo(Integer value) {
            addCriterion("reporter <>", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterGreaterThan(Integer value) {
            addCriterion("reporter >", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterGreaterThanOrEqualTo(Integer value) {
            addCriterion("reporter >=", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterLessThan(Integer value) {
            addCriterion("reporter <", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterLessThanOrEqualTo(Integer value) {
            addCriterion("reporter <=", value, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterIn(List<Integer> values) {
            addCriterion("reporter in", values, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterNotIn(List<Integer> values) {
            addCriterion("reporter not in", values, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterBetween(Integer value1, Integer value2) {
            addCriterion("reporter between", value1, value2, "reporter");
            return (Criteria) this;
        }

        public Criteria andReporterNotBetween(Integer value1, Integer value2) {
            addCriterion("reporter not between", value1, value2, "reporter");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNull() {
            addCriterion("report_time is null");
            return (Criteria) this;
        }

        public Criteria andReportTimeIsNotNull() {
            addCriterion("report_time is not null");
            return (Criteria) this;
        }

        public Criteria andReportTimeEqualTo(Date value) {
            addCriterion("report_time =", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotEqualTo(Date value) {
            addCriterion("report_time <>", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThan(Date value) {
            addCriterion("report_time >", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("report_time >=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThan(Date value) {
            addCriterion("report_time <", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeLessThanOrEqualTo(Date value) {
            addCriterion("report_time <=", value, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeIn(List<Date> values) {
            addCriterion("report_time in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotIn(List<Date> values) {
            addCriterion("report_time not in", values, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeBetween(Date value1, Date value2) {
            addCriterion("report_time between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andReportTimeNotBetween(Date value1, Date value2) {
            addCriterion("report_time not between", value1, value2, "reportTime");
            return (Criteria) this;
        }

        public Criteria andVerifierIsNull() {
            addCriterion("verifier is null");
            return (Criteria) this;
        }

        public Criteria andVerifierIsNotNull() {
            addCriterion("verifier is not null");
            return (Criteria) this;
        }

        public Criteria andVerifierEqualTo(String value) {
            addCriterion("verifier =", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotEqualTo(String value) {
            addCriterion("verifier <>", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierGreaterThan(String value) {
            addCriterion("verifier >", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierGreaterThanOrEqualTo(String value) {
            addCriterion("verifier >=", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierLessThan(String value) {
            addCriterion("verifier <", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierLessThanOrEqualTo(String value) {
            addCriterion("verifier <=", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierLike(String value) {
            addCriterion("verifier like", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotLike(String value) {
            addCriterion("verifier not like", value, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierIn(List<String> values) {
            addCriterion("verifier in", values, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotIn(List<String> values) {
            addCriterion("verifier not in", values, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierBetween(String value1, String value2) {
            addCriterion("verifier between", value1, value2, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierNotBetween(String value1, String value2) {
            addCriterion("verifier not between", value1, value2, "verifier");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeIsNull() {
            addCriterion("verifier_time is null");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeIsNotNull() {
            addCriterion("verifier_time is not null");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeEqualTo(Date value) {
            addCriterion("verifier_time =", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeNotEqualTo(Date value) {
            addCriterion("verifier_time <>", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeGreaterThan(Date value) {
            addCriterion("verifier_time >", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("verifier_time >=", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeLessThan(Date value) {
            addCriterion("verifier_time <", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeLessThanOrEqualTo(Date value) {
            addCriterion("verifier_time <=", value, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeIn(List<Date> values) {
            addCriterion("verifier_time in", values, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeNotIn(List<Date> values) {
            addCriterion("verifier_time not in", values, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeBetween(Date value1, Date value2) {
            addCriterion("verifier_time between", value1, value2, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierTimeNotBetween(Date value1, Date value2) {
            addCriterion("verifier_time not between", value1, value2, "verifierTime");
            return (Criteria) this;
        }

        public Criteria andVerifierContextIsNull() {
            addCriterion("verifier_context is null");
            return (Criteria) this;
        }

        public Criteria andVerifierContextIsNotNull() {
            addCriterion("verifier_context is not null");
            return (Criteria) this;
        }

        public Criteria andVerifierContextEqualTo(String value) {
            addCriterion("verifier_context =", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextNotEqualTo(String value) {
            addCriterion("verifier_context <>", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextGreaterThan(String value) {
            addCriterion("verifier_context >", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextGreaterThanOrEqualTo(String value) {
            addCriterion("verifier_context >=", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextLessThan(String value) {
            addCriterion("verifier_context <", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextLessThanOrEqualTo(String value) {
            addCriterion("verifier_context <=", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextLike(String value) {
            addCriterion("verifier_context like", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextNotLike(String value) {
            addCriterion("verifier_context not like", value, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextIn(List<String> values) {
            addCriterion("verifier_context in", values, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextNotIn(List<String> values) {
            addCriterion("verifier_context not in", values, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextBetween(String value1, String value2) {
            addCriterion("verifier_context between", value1, value2, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andVerifierContextNotBetween(String value1, String value2) {
            addCriterion("verifier_context not between", value1, value2, "verifierContext");
            return (Criteria) this;
        }

        public Criteria andAppealerIsNull() {
            addCriterion("appealer is null");
            return (Criteria) this;
        }

        public Criteria andAppealerIsNotNull() {
            addCriterion("appealer is not null");
            return (Criteria) this;
        }

        public Criteria andAppealerEqualTo(Integer value) {
            addCriterion("appealer =", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerNotEqualTo(Integer value) {
            addCriterion("appealer <>", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerGreaterThan(Integer value) {
            addCriterion("appealer >", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerGreaterThanOrEqualTo(Integer value) {
            addCriterion("appealer >=", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerLessThan(Integer value) {
            addCriterion("appealer <", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerLessThanOrEqualTo(Integer value) {
            addCriterion("appealer <=", value, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerIn(List<Integer> values) {
            addCriterion("appealer in", values, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerNotIn(List<Integer> values) {
            addCriterion("appealer not in", values, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerBetween(Integer value1, Integer value2) {
            addCriterion("appealer between", value1, value2, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealerNotBetween(Integer value1, Integer value2) {
            addCriterion("appealer not between", value1, value2, "appealer");
            return (Criteria) this;
        }

        public Criteria andAppealTimeIsNull() {
            addCriterion("appeal_time is null");
            return (Criteria) this;
        }

        public Criteria andAppealTimeIsNotNull() {
            addCriterion("appeal_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppealTimeEqualTo(Date value) {
            addCriterion("appeal_time =", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeNotEqualTo(Date value) {
            addCriterion("appeal_time <>", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeGreaterThan(Date value) {
            addCriterion("appeal_time >", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("appeal_time >=", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeLessThan(Date value) {
            addCriterion("appeal_time <", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeLessThanOrEqualTo(Date value) {
            addCriterion("appeal_time <=", value, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeIn(List<Date> values) {
            addCriterion("appeal_time in", values, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeNotIn(List<Date> values) {
            addCriterion("appeal_time not in", values, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeBetween(Date value1, Date value2) {
            addCriterion("appeal_time between", value1, value2, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealTimeNotBetween(Date value1, Date value2) {
            addCriterion("appeal_time not between", value1, value2, "appealTime");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentIsNull() {
            addCriterion("appeal_attachment is null");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentIsNotNull() {
            addCriterion("appeal_attachment is not null");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentEqualTo(String value) {
            addCriterion("appeal_attachment =", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentNotEqualTo(String value) {
            addCriterion("appeal_attachment <>", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentGreaterThan(String value) {
            addCriterion("appeal_attachment >", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentGreaterThanOrEqualTo(String value) {
            addCriterion("appeal_attachment >=", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentLessThan(String value) {
            addCriterion("appeal_attachment <", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentLessThanOrEqualTo(String value) {
            addCriterion("appeal_attachment <=", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentLike(String value) {
            addCriterion("appeal_attachment like", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentNotLike(String value) {
            addCriterion("appeal_attachment not like", value, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentIn(List<String> values) {
            addCriterion("appeal_attachment in", values, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentNotIn(List<String> values) {
            addCriterion("appeal_attachment not in", values, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentBetween(String value1, String value2) {
            addCriterion("appeal_attachment between", value1, value2, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealAttachmentNotBetween(String value1, String value2) {
            addCriterion("appeal_attachment not between", value1, value2, "appealAttachment");
            return (Criteria) this;
        }

        public Criteria andAppealContextIsNull() {
            addCriterion("appeal_context is null");
            return (Criteria) this;
        }

        public Criteria andAppealContextIsNotNull() {
            addCriterion("appeal_context is not null");
            return (Criteria) this;
        }

        public Criteria andAppealContextEqualTo(String value) {
            addCriterion("appeal_context =", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextNotEqualTo(String value) {
            addCriterion("appeal_context <>", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextGreaterThan(String value) {
            addCriterion("appeal_context >", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextGreaterThanOrEqualTo(String value) {
            addCriterion("appeal_context >=", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextLessThan(String value) {
            addCriterion("appeal_context <", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextLessThanOrEqualTo(String value) {
            addCriterion("appeal_context <=", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextLike(String value) {
            addCriterion("appeal_context like", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextNotLike(String value) {
            addCriterion("appeal_context not like", value, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextIn(List<String> values) {
            addCriterion("appeal_context in", values, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextNotIn(List<String> values) {
            addCriterion("appeal_context not in", values, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextBetween(String value1, String value2) {
            addCriterion("appeal_context between", value1, value2, "appealContext");
            return (Criteria) this;
        }

        public Criteria andAppealContextNotBetween(String value1, String value2) {
            addCriterion("appeal_context not between", value1, value2, "appealContext");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_record
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 28 11:26:14 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table credit_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}