package diana.maven.project.model;

public class Function {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String functionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String functionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.parent_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.id
     *
     * @return the value of function.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.id
     *
     * @param id the value for function.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_code
     *
     * @return the value of function.function_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_code
     *
     * @param functionCode the value for function.function_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_name
     *
     * @return the value of function.function_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_name
     *
     * @param functionName the value for function.function_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.parent_id
     *
     * @return the value of function.parent_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.parent_id
     *
     * @param parentId the value for function.parent_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.is_del
     *
     * @return the value of function.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.is_del
     *
     * @param isDel the value for function.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}