package diana.maven.project.model;

import java.util.Date;

public class OperationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date operationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.id
     *
     * @return the value of operation_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.id
     *
     * @param id the value for operation_record.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.user_id
     *
     * @return the value of operation_record.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.user_id
     *
     * @param userId the value for operation_record.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_type
     *
     * @return the value of operation_record.operation_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_type
     *
     * @param operationType the value for operation_record.operation_type
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_time
     *
     * @return the value of operation_record.operation_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_time
     *
     * @param operationTime the value for operation_record.operation_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }
}