package diana.maven.project.models;

import java.util.Date;

public class PlatformUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.login_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.display_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.password
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.user_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String creditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.phone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String subordinateUnits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String unitsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.creat_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date creatTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.last_login
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private String locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.id
     *
     * @return the value of platform_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.id
     *
     * @param id the value for platform_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.login_name
     *
     * @return the value of platform_user.login_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.login_name
     *
     * @param loginName the value for platform_user.login_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.display_name
     *
     * @return the value of platform_user.display_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.display_name
     *
     * @param displayName the value for platform_user.display_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.password
     *
     * @return the value of platform_user.password
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.password
     *
     * @param password the value for platform_user.password
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.user_name
     *
     * @return the value of platform_user.user_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.user_name
     *
     * @param userName the value for platform_user.user_name
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.credit_code
     *
     * @return the value of platform_user.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.credit_code
     *
     * @param creditCode the value for platform_user.credit_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.phone
     *
     * @return the value of platform_user.phone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.phone
     *
     * @param phone the value for platform_user.phone
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.subordinate_units
     *
     * @return the value of platform_user.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getSubordinateUnits() {
        return subordinateUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.subordinate_units
     *
     * @param subordinateUnits the value for platform_user.subordinate_units
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setSubordinateUnits(String subordinateUnits) {
        this.subordinateUnits = subordinateUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.units_code
     *
     * @return the value of platform_user.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getUnitsCode() {
        return unitsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.units_code
     *
     * @param unitsCode the value for platform_user.units_code
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setUnitsCode(String unitsCode) {
        this.unitsCode = unitsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.creat_time
     *
     * @return the value of platform_user.creat_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.creat_time
     *
     * @param creatTime the value for platform_user.creat_time
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.last_login
     *
     * @return the value of platform_user.last_login
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.last_login
     *
     * @param lastLogin the value for platform_user.last_login
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.locked
     *
     * @return the value of platform_user.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.locked
     *
     * @param locked the value for platform_user.locked
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setLocked(String locked) {
        this.locked = locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_user.is_del
     *
     * @return the value of platform_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_user.is_del
     *
     * @param isDel the value for platform_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}