package diana.maven.project.models;

public class PlatformRoleUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_role_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_role_user.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_role_user.role_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform_role_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_role_user.id
     *
     * @return the value of platform_role_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_role_user.id
     *
     * @param id the value for platform_role_user.id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_role_user.user_id
     *
     * @return the value of platform_role_user.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_role_user.user_id
     *
     * @param userId the value for platform_role_user.user_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_role_user.role_id
     *
     * @return the value of platform_role_user.role_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_role_user.role_id
     *
     * @param roleId the value for platform_role_user.role_id
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform_role_user.is_del
     *
     * @return the value of platform_role_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform_role_user.is_del
     *
     * @param isDel the value for platform_role_user.is_del
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}