package diana.maven.project.mappers;

import diana.maven.project.models.OperationRecord;
import diana.maven.project.models.OperationRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<OperationRecord> selectByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    OperationRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") OperationRecord record, @Param("example") OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") OperationRecord record, @Param("example") OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(OperationRecord record);
}