package diana.maven.project.mapper;

import diana.maven.project.model.CreditRating;
import diana.maven.project.model.CreditRatingExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CreditRatingMapper extends MapperMarkerInterface{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(CreditRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(CreditRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(CreditRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(CreditRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<CreditRating> selectByExample(CreditRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    CreditRating selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") CreditRating record, @Param("example") CreditRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") CreditRating record, @Param("example") CreditRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(CreditRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_rating
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(CreditRating record);
}