package diana.maven.project.mapper;

import diana.maven.project.model.PlatformUser;
import diana.maven.project.model.PlatformUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformUserMapper extends MapperMarkerInterface {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<PlatformUser> selectByExample(PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    PlatformUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlatformUser record, @Param("example") PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") PlatformUser record, @Param("example") PlatformUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(PlatformUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(PlatformUser record);
}