package diana.maven.project.mapper;

import diana.maven.project.model.PlatformRoleUser;
import diana.maven.project.model.PlatformRoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlatformRoleUserMapper extends MapperMarkerInterface {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    long countByExample(PlatformRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByExample(PlatformRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insert(PlatformRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int insertSelective(PlatformRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    List<PlatformRoleUser> selectByExample(PlatformRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    PlatformRoleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlatformRoleUser record, @Param("example") PlatformRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByExample(@Param("record") PlatformRoleUser record, @Param("example") PlatformRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKeySelective(PlatformRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_role_user
     *
     * @mbg.generated Tue Apr 28 11:26:14 CST 2020
     */
    int updateByPrimaryKey(PlatformRoleUser record);

}